#!/usr/bin/env bash

SCRIPT_PATH=$(dirname "$0")
PYTHONPATH=$(realpath "$SCRIPT_PATH")/utils
export PYTHONPATH
DAY_FOLDERS=$(find . -type d | grep day | sort)
for FOLDER in $DAY_FOLDERS
do
    python "$FOLDER/problem.py"
done
